[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  GOOGLE_TAG_MANAGER_ID = "GTM-WZ64VB3"

# please add new redirects to next.config.js as well for local development
[[redirects]]
  from = "/"
  to = "/sparring"
  status = 302
  force = false

[[redirects]]
  from = "/lean-canvas"
  to = "https://60db1bb54ba1e6cdf4d3159d--serene-ptolemy-a0f690.netlify.app"
  status = 200
  force = true

# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
  [context.production.environment]

# Context for the staging branch
[context.staging]
  [context.staging.environment]
