[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  GOOGLE_TAG_MANAGER_ID = "GTM-WZ64VB3"
  NODE_VERSION = "16"

# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
  [context.production.environment]

# Context for the staging branch
[context.staging]
  [context.staging.environment]
